services:
  - type: web
    name: metabase
    env: docker
    repo: https://github.com/theperfectgentleman/metabase.git
    region: ohio
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /api/health
    envVars:
      - key: JAVA_OPTS
        value: -Xmx450m -Xms150m
      - key: PORT
        value: 3000
      - key: MB_DB_TYPE
        value: h2
      - key: MB_DB_FILE
        value: /var/lib/metabase/metabase.db
    disk:
      name: metabase-data
      mountPath: /var/lib/metabase
      sizeGB: 1
