services:
  - type: web
    name: metabase
    env: docker
    repo: https://github.com/theperfectgentleman/metabase.git
    region: ohio
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /api/health
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_DBNAME
        value: metabasedb
      - key: MB_DB_PORT
        value: 6543
      - key: MB_DB_USER
        value: postgres.btcvuivvimeiwzjnzmv
      - key: MB_DB_PASS
        sync: false
      - key: MB_DB_HOST
        value: aws-0-eu-central-1.pooler.supabase.com
      - key: JAVA_OPTS
        value: -Xmx1g
