services:
  - type: web
    name: metabase
    plan: free
    env: docker
    region: ohio
    branch: main
    healthCheckPath: /api/health
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MB_JETTY_PORT
        value: 10000
      - key: PORT
        value: 10000
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=75.0 -XX:MinRAMPercentage=50.0
      - key: MB_DB_TYPE
        value: h2
      - key: MB_DB_FILE
        value: /data/metabase.db
    disk:
      name: metabase-data
      mountPath: /data
      sizeGB: 1
